lob/lob-node

- lib/resources/lob.js
99% sure this was a typo as useragent (no capital a) was never defined anywhere.
> Fixing a typo in lob.js

- README.md
- lib/index.js
- lib/resources/index.js
- test/index.js
As I begin to work on the internal wrapper, I noticed a bug in the resource loader and opportunity to improve the constructor interface slightly.
You can see the fix for the path issue here: ced746b51521941263720a32e547a1ef69718ccc
I also thought that it may be useful to just allow users to optionally pass an options argument to the Lob constructor which may contain the apiKey instead of always reserving the first arg for the key only.
An example:
```javascript
var Lob = require('lob')({ apiKey: 'foo', host: 'bar' });
```
> PR #115 Fixes / Enhancements

- lib/resources/resourceBase.js
- test/resourceBase.js
Ensures that 500+ errors get rejected
Currently it does not reject 500+ errors
@robinjoseph08 @elnaz @mgartner
> fix(errors): reject 500+ errors

- gulpfile.js
- test/areas.js
- test/checks.js
- test/objects.js
- test/postcards.js
Make the test suite more deterministic and increase the timeout to 30 seconds.
Since we introduced signed links, the tests sometimes failed because the expiration times in the URLs were a second or two off. This no longer relies on the test "running fast enough". I also removed a check test of "creating with inline bank account" which you can't even do anymore.
> make tests less variable

- test/checks.js
Replace `file` with `check_bottom` for checks in the tests
The new version calls for it.
@brianseitel
> fix(tests): replace file with check_bottom for checks

- CONTRIBUTING.md
- README.md
- Update README testing instructions to include npm style scripts instead of gulp (no longer used)
- Fixes example of how to set custom API version
> fix(readme): update testing instructions

- lib/resources/bankAccounts.js
- test/bankAccounts.js
Most of the wrapper functions use a `params` object but verify had an explicit `amounts` argument. I changed the function to be more consistent with everything else we do, even though explicit arguments would arguably be preferred.  
Fixes https://github.com/lob/lob-node/issues/160
> feat(bank-accounts): standardize verify function

- .travis.yml
What: Test more recent version of Node.js.
Why: We should be sure that our wrapper works with common versions of Node.js that other developers might be running.
> feat(version): support Node versions 0.12, 4, 5, and 6.

- CONTRIBUTING.md
What: Fixed old hyperlink that no longer went anywhere to valid one.
Why: Customer facing, so an out of date link is a bad look.
> chore(fix hyperlink): changed out-of-date link to valid

- examples/README.md
- examples/verify_and_create_letters_from_csv/index.js
- examples/verify_and_create_letters_from_csv/input.csv
> chore(examples): Fix examples to use new us_verifications endpoint

- .gitignore
- lib/resources/checks.js
- lib/resources/letters.js
- lib/resources/postcards.js
- test/checks.js
- test/letters.js
- test/postcards.js
Adds `delete()` method to: `/letters`, `/postcards`, and `/checks` resources
Example useage:
```
Lob.postcards.delete('psc_xxxxxxxxxx', function (err, res) {
if (err) { return console.log(err.message); }
console.log('Postcard Deleted! ' + res.id);
});
```
One integration test of the delete method on each `/letters`, `/postcards`, and `/checks` resource
> feat(delete): Add delete method to postcards, letters, and checks

- test/addresses.js
**What:** Updates the lob-node tests to handle auto-verification
**Why:** Wrapper tests were failing due to the auto-verification release. We needed to update the tests to take in an already verified address that's already capitalized. 
**Details:**
I figured that changing the default object was the better approach rather than changing the expected response in the `create` function because we want to test that the wrapper simply works rather than confirming that auto-verify works.
> fix(auto-verify): update tests to manage auto-verify

- .travis.yml
- package.json
> chore(deprecate): Deprecate support for 0.10 and 0.12

- lib/index.js
- lib/resources/resourceBase.js
> refactor(object): Use Object.prototype.hasOwnProperty.call, instead of assuming objects inherit from Object.prototype

- lib/resources/index.js
When bundling with webpack, the proper context for the dynamic requires is lost. This change specifically defines the `module.exports` in order for webpack to correctly bundle everything.
> refactor(resources): remove dynamic requires

- lib/resources/usVerifications.js
- test/usVerifications.js
**What**
**Notes**
The old function signature (of arity 2) is still valid.
> feat(us-verifications): allow passing queries in verification creation

- lib/resources/resourceBase.js
`this.configs.headers` is used throughout all request executions. By saving these values in `this.configs.headers` we will persist headers meant for a particular request to future requests. This is particularly bad if someone is sendings resource with and without idemptoency keys as the later ones won't be created.
> fix(headers): don't save request specific headers in configs

- test/addresses.js
Fix broken address tests. When you create an address, if the value of `address_line2` is empty, we return `null` instead of an empty string (`''`).
> fix(addresses): fix broken test

- package-lock.json
- package.json
- test/resourceBase.js
* Upgrades mocha to most recent version
* Newer versions of mocha have an updated version of growl (older versions have a known security vulnerability).
> fix(deps): upgrade mocha (and growl) version

- lib/resources/resourceBase.js
If an endpoint does not contain a body (ex. a 204 response) then currently the library will fail at [this step](https://github.com/lob/lob-node/blob/master/lib/resources/resourceBase.js#L89-L93) as it attempts to set the `_response` property on a non-existent body. The error thrown is `Object.defineProperty called on non-object`.
> fix(resource-base): default body to empty object

- lib/resources/resourceBase.js
- test/letters.js
Undefined values passed into lob.letters.create causes a confusing
exception in the form-data module that request uses for multipart headers
For instance, if the `color` key is set with no value, we get back this
confusing error: `Error: Cannot read property 'name' of undefined`
Now we get `Error: color is undefined`
> handle undefined multipart form value

- package-lock.json
- package.json
Upgrade some dev dependencies
- Maintenance
- Those packages had security vulnerabilities (they're only dev packages though. still, it gets rid of the warning at the top of the repo lol)
> chore(deps): upgrade packages

- README.md
- lib/resources/resourceBase.js
- package-lock.json
- package.json
- test/resourceBase.js
Add the ability to provide a custom HTTP(s) agent. This is useful if you want to, say, use an HTTP agent like [agentkeepalive](https://github.com/node-modules/agentkeepalive) which uses HTTP keep-alive to make outgoing HTTP requests much more efficient.
> feat(resource): add ability to specify custom HTTP agent

- lib/resources/checks.js
- lib/resources/letters.js
- lib/resources/postcards.js
- test/checks.js
- test/letters.js
- test/postcards.js
Converts `merge_variables` into JSON
So we can properly use merge variable conditionals in the templating syntax
> fix(merge-variables): convert merge variables to JSON

- CHANGELOG.md
- package.json
**What**
Updates CHANGELOG.md and bumps client library version identifier from 6.1.1 to 6.2.0
**Why**
Cutting new release with added self mailer support
> chore: update changelog and bump version to 6.2.0

- examples/README.md
- examples/create_postcard_idempotent.js
- examples/create_postcard_intl.js
- examples/create_postcard_metadata.js
- examples/create_postcard_remote.js
- examples/create_postcard_send_date.js
- examples/create_postcard_template.js
- examples/list_postcard_metadata.js
I did change up a few things. I didn't include a separate international address creation request––I included it in a postcard example as well. I also didn't include the full-payload examples, since that's just adding more fields into the request (and, given the payloads in the live docs, quite self-explanatory).
This is now a separate ticket from the other languages. Since I began with Node, this one took the longest as I figured out which examples I needed to include. The other 5 languages should be quicker.
> feat(examples): added a bunch of examples which were in the old docs

- .github/workflows/npm-publish.yml
This is largely modeled off of your pre-existing [npm-publish.yml](https://github.com/lob/ui-components/blob/main/.github/workflows/npm-publish.yml) with a few differences:
1. the prop-path is changed (the package.json has a different version naming attribute, see line 27)
2. we removed the 'npm run build-library' step
> Adding github action yml to automate npm publishing steps

- lib/resources/cards.js
- test/cards.js
Adds card update route to cards resource.
To expose existing cards update endpoint in SDK.
> fix(Cards): Add card update route

- test/index.js
- Removed test due to it not being relevant to our SDK. It only tested that `test.com` was reachable. This is out of our scope since we do not own that domain, we cannot control when it is live.
> Node test fixes

- .gitignore
- examples/create_postcards_from_csv/index.js
- lib/resources/resourceBase.js
- package.json
A re-implementation of (PR 214)[https://github.com/lob/lob-node/pull/214]
This removes an unneeded dependency from legacy versions of node that did not natively support Promises
Co-authored-by: Josh Duff <me@JoshDuff.com>
> chore: reimplement PR to remove Bluebird dep

- package-lock.json
- package.json
Ran npm audit --force update
The following dev dependencies updated
"eslint": "^5.16.0" =>"^8.6.0"
"json-2-csv": "^1.3.0" => "^3.15.1"
"mocha": "~5.2.0" => "^9.1.3"
"nyc": "^14.1.1" =>  "^15.1.0"
Updated required version of Node from 6.0.0 => 10.0.0
> update package.json dependencies

- lib/resources/usAutocompletions.js
- test/usAutocompletions.js
We've added a new query param for autocomplete similar to us_verfiications that'll allow users to return addresses in all upper case or proper case
> feat(autocomplete): Allow Query Params

- .github/workflows/run_tests.yml
- .gitignore
- README.md
- lib/index.js
- lib/resources/campaigns.js
- lib/resources/index.js
- package-lock.json
- test/campaigns.js
Added the ability to list, create, retrieve and delete for Campaigns.
> feat(campaigns): Added support for Campaigns 
