lib/resources/settings.js
test/settings.js

feat(settings): add options to list function

---

lib/resources/addresses.js
lib/resources/areas.js
lib/resources/bankAccounts.js
lib/resources/checks.js
lib/resources/countries.js
lib/resources/jobs.js
lib/resources/lob.js
lib/resources/objects.js
lib/resources/packagings.js
lib/resources/postcards.js
lib/resources/routes.js
lib/resources/services.js
lib/resources/settings.js
lib/resources/states.js
lib/resources/verification.js
package.json
test/bankAccounts.js
test/checks.js
test/jobs.js
test/objects.js

Fix version header

---

README.md

fixed routing number and added signatory to bank account example

---

README.md

Add missing docs for settings

---

README.md

fixed link to accounts page

---

lib/resources/addresses.js
lib/resources/areas.js
lib/resources/bankAccounts.js
lib/resources/checks.js
lib/resources/jobs.js
lib/resources/objects.js
lib/resources/packagings.js
lib/resources/postcards.js
lib/resources/routes.js
lib/resources/services.js
lib/resources/settings.js
lib/resources/verification.js

This should fix the unhandled errors experienced during timeouts.

fixes #103; better error handling for timeouts

---

test/jobs.js

@lob/api-engineering-team 
Tests needed to be adjusted due to changes with multi-object made in the API this week.

fix(jobs): fixes multi-object job tests

---

README.md
examples/create-check.js

feat(checks): added docs and example for check logo

---

README.md

@lob/frontend-engineering-team

fix(readme): examples for HTML

---

lib/resources/resourceBase.js

fixed undefined check

---

lib/index.js
test/bankAccounts.js
test/checks.js

export resourceBase on Lob

---

examples/create-check.js
lib/resources/bankAccounts.js
test/bankAccounts.js
test/checks.js

#119 
@lob/api-engineering-team

feat(bankAccounts): add bank account verify

---

README.md

this is the format i'll use for all wrapper readmes - will wait for comments here before updating other wrappers as well. feedback appreciated :cactus: 
@pon @leore @mgartner @russelltaylor05 @robinjoseph08 @elnaz

fix(readme): standardize format + link to docs

---

examples/create-job.js
examples/create-letter.js
examples/create-postcard.js
examples/html/card.html
examples/html/letter.html
test/areas.js
test/checks.js
test/jobs.js
test/letters.js
test/objects.js
test/postcards.js

Fixes lob/lob-api#1506
@pon @mgartner @leore @elnaz

feat(examples): add html, data, and custom fonts

---

.gitignore
.jscsrc
.jshintrc
examples/README.md
examples/csv_letter_mail_merge/index.js
examples/csv_letter_mail_merge/input.csv
examples/csv_letter_mail_merge/letter_template.html
examples/csv_postcards/input.csv
package.json

What: Add a CSV mail-merge example, added the missing input.csv files
@robinjoseph08 @pon @mgartner

feat(examples): add mail-merge example

---

examples/csv_letter_mail_merge/index.js

What: Fixes bug in mail-merge example and output file contents reset every time the script runs.
@pon @mgartner @elnaz @robinjoseph08 @neelk07

fix(examples): mail-merge example

---

lib/resources/routes.js
test/routes.js

Add missing routes.retrieve() method

---

.travis.yml

https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#Why-migrate-to-container-based-infrastructure%3F

uses travis' container infrastructure for faster builds

---

examples/create_check.js
examples/create_job.js
examples/create_letter.js
examples/create_postcard.js
examples/create_postcards_from_csv/index.js
examples/verify_and_create_letters_from_csv/index.js
test/addresses.js
test/areas.js
test/bankAccounts.js
test/checks.js
test/countries.js
test/index.js
test/jobs.js
test/letters.js
test/objects.js
test/postcards.js
test/resourceBase.js
test/routes.js
test/settings.js
test/states.js
test/verification.js

Also put in a new API key to avoid 429s.

update postcard example to use size

---

lib/resources/resourceBase.js
test/resourceBase.js

Fixes https://github.com/lob/lob-node/issues/162

fix(errors): always throw Error object

---

examples/create_check.js
test/bankAccounts.js

Updates the bank account test and the check example. Also fixes a bug in the check example that we introduced when we changed the signature of the `.verify()` function.

feat(api-version): support 2016-03-21

---

README.md
lib/resources/resourceBase.js
test/resourceBase.js

Inspiration: https://github.com/stripe/stripe-node/pull/223/files

feat(response): allow access to response headers

---

examples/verify_and_create_letters_from_csv/index.js

Fix typo
Cause typos are bad
@elnaz

fix(examples): fix typo

---

test/resourceBase.js

chore(mock): use mock.lob.com

---

README.md
examples/README.md
examples/create_letter.js
examples/create_postcard.js
examples/create_postcards_from_csv/index.js
examples/verify_and_create_letters_from_csv/index.js

What: update examples to use merge_variables
Why: new HTML feature new version

chore(examples): update to use merge_variables

---

README.md
examples/README.md

- update documentation links
- add more links to docs to add clarity
after language here is approved, i'll go ahead and update all wrappers

fix(readme): update documentation

---

README.md
lib/resources/usZipLookups.js
test/usZipLookups.js

feat(us-zip-lookups): Add US Zip Code Lookup

---

test/intlVerifications.js

test(intl): Update international verifications tests

---

test/usVerifications.js

Fixes the US Verification test
With changes to the test responses in the US Verifications API, we should update our tests to reflect the expected behavior.

fix(test): fix US verification test

---

lib/index.js
lib/resources/addresses.js
lib/resources/areas.js
lib/resources/bankAccounts.js
lib/resources/checks.js
lib/resources/intlVerifications.js
lib/resources/letters.js
lib/resources/postcards.js
lib/resources/resourceBase.js
lib/resources/routes.js
lib/resources/usVerifications.js
lib/resources/usZipLookups.js
test/addresses.js
test/areas.js
test/bankAccounts.js
test/checks.js
test/index.js
test/intlVerifications.js
test/letters.js
test/postcards.js
test/resourceBase.js
test/routes.js
test/usVerifications.js
test/usZipLookups.js

What: es6 ify rosource and test files
Note:
- the scope of this PR includes es6-ifying test files (use arrow functions and string interpolation) and restructuring the dependencies listed on top of the resource files
- https://github.com/lob/lob-node/pull/194 will handle using es6 classes and string interpolation for resource files

chore(lib): es6 ify resource and test files

---

README.md
examples/create_check.js
examples/create_letter.js
examples/create_postcard.js
examples/create_postcards_from_csv/index.js
examples/verify_and_create_letters_from_csv/index.js
test/setup.js

Removes all lob api keys from source code and updates testing instructions in README
Say no to api key exposure

test(api-key): remove lob api key from tests and examples

---

examples/create_postcards_from_csv/index.js

Adds metadata as part of the example

chore(example): add metadata field

---

examples/create_postcards_from_csv/index.js

What: add concurrency to example

feat(postcards): add ability to modify concurrency

---

test/intlVerifications.js

updating failing test after intl verification test mode release

fix(intl-verifications): fixed failing test

---

.travis.yml
README.md
package-lock.json
package.json

- Applies the automated dependency changes from #220 #218
- Changes Travis to test with v10, v12 (LTS), v13 (aka `"node"`)
- Previously ran against v6, v8, v10, v13
- Updated README.md to suggest `const` vs `var`

chore(deps): csv-parse@4.4.6, travis node v12, docs

---

test/checks.js
test/letters.js
test/postcards.js

Adds tests to cover new versions

test(plc): add tests for new versions (template syntax and cursor pagination)

---

.github/workflows/npm-publish.yml
.github/workflows/run_tests.yml
package.json
test/index.js

These changes fix the coveralls error that was showing up before when running the tests.

updated tests and npm publish action files

---

.gitignore
package-lock.json
package.json

Removed package-lock.json from gitignore
Updated package-lock.json
Updated version in package.json to 6.5.4

Update package version

---

examples/create_postcard_intl.js

Update lob address to new Market St address

GC-1942/update address in example req

---

examples/create_postcard_intl.js

Reverts lob/lob-node#283
Forgot to bump the version #

Revert "GC-1942/update address in example req"

---

CHANGELOG.md
examples/create_postcard_intl.js
package-lock.json
package.json

Update Lob address in example request to use new Lob address

Gc 1942 3/update lob address
